imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: sonata.yml }

gregwar_captcha: ~

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    cache:  false
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SonataMediaBundle:Form:media_widgets.html.twig'
            - 'NetcastUrestMainBundle:Form:urest_widgets.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ NetcastUrestMainBundle  ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User

    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.user_manager
        mailer:       urest.registration.mailer

    registration:
        form:
            type:    netcast_urest_user_registration
            name:    netcast_urest_user_registration
            handler: urest.registration.form.handler
        confirmation:
            enabled: true

sonata_doctrine_orm_admin:
    templates:
        form: [ NetcastUrestMainBundle:Admin:form_admin_fields.html.twig ]

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        mapping_types: 
            enum: string

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sonata_user:
    manager_type: orm
    class:
        user: Application\Sonata\UserBundle\Entity\User

#CK Editor
ivory_ck_editor:
    default_config: default
    toolbars:
        configs:
            user_toolbar: [ "@clipboard", "@editing", "@links", "@insert", "@tool", "@document", "/", "@basicstyles" , "@paragraph" ]
            admin_toolbar: [ "@clipboard", "@editing", "@links", "@insertAdmin", "@tool", "@document", "/", "@basicstyles" , "@paragraph" ]
        items:
            document: [ 'Source' ]
            clipboard: [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-','Undo','Redo' ]
            editing: [ 'Find','Replace','-','SelectAll','-','SpellChecker', 'Scayt' ]
            basicstyles: [ 'Bold','Italic','Underline','Strike','-','RemoveFormat' ]
            paragraph:     [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','BidiLtr','BidiRtl' ]
            links:     [ 'Link','Unlink' ]
            insert:     [ 'Image', 'SpecialChar' ]
            insertAdmin: [ 'Image', 'SpecialChar', 'Table' ]
            colors:     [ 'TextColor' ]
            tool:     [ 'Maximize' ]
            styles:     [ 'Styles', 'Format', 'Font', 'FontSize' ]
    configs:
        user_config:
             toolbar: "user_toolbar"
        admin_config:
             toolbar: "admin_toolbar"
        default:

# Application parameters
parameters:
    url_no_photo: '/bundles/netcasturestmain/images/photo_00.gif'
    max_items_on_pagination: 2

sonata_media:
    buzz:
        client:
            verify_peer: false
