security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_manager
        loginza:
            id: impar.loginza.provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
                default_target_path: /%locale%/admin/dashboard
            logout:
                path:           /admin/logout
            anonymous:          true

        main:
            pattern:             .*
            security:            true
            context:             user
            form_login:
                provider:        fos_userbundle
                login_path:      /
                use_forward:     false
                check_path:      /login_check
                failure_path:    null
                success_handler: netcast.urest.auth.handler
                failure_handler: netcast.urest.auth.handler
            logout:              true
            anonymous:           true
            loginza:
                provider:        loginza
                check_path:      /loginza_check
                failure_handler: netcast.urest.auth.handler
                success_handler: netcast.urest.auth.handler

    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/%locale%/login$,                    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%locale%/register,                  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%locale%/resetting,                 role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Admin login page needs to be access without credential
        - { path: ^/admin/login$,                       role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$,                      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$,                 role: IS_AUTHENTICATED_ANONYMOUSLY }

        -   path: /admin/sonata/user/user/.*
            roles: [ ROLE_ADD_EDIT_SUPER_ADMIN, ROLE_ADD_EDIT_ADMIN, ROLE_ADD_EDIT_SUPER_MANAGER,ROLE_SUPER_ADMIN ]
        -   path: /admin/sonata/user/group/.*
            roles: [ ROLE_SUPER_ADMIN ]
        -   path: /admin/locationinfo-(country|city)/.*
            roles: [ ROLE_ADD_EDIT_ARTICLE,ROLE_SUPER_ADMIN ]
        -   path: /admin/urest/main/(country|region|city)/.*
            roles: [ ROLE_ADD_EDIT_CITY_COUNTRY,ROLE_SUPER_ADMIN ]
        -   path: /admin/urest/main/tour/.*
            roles: [ ROLE_ADD_EDIT_TOURS,ROLE_SUPER_ADMIN ]
        -   path:  /admin/urest/main/(tourmedia|hotel|hotelroom|apartment|service|options|wellcomemsg)/.*
            roles: [ ROLE_ADD_EDIT_INFO_IN_TOUR_BUILDER,ROLE_SUPER_ADMIN ]
        -   path: /admin/urest/main/blogcategory/.*
            roles: [ ROLE_ADD_EDIT_BLOG_SECTION,ROLE_SUPER_ADMIN ]
        -   path: /admin/urest/main/contact/.*
            roles: [ ROLE_ADD_EDIT_CONTACTS,ROLE_SUPER_ADMIN ]
        -   path: /admin/urest/main/main.*
            roles: [ ROLE_EDIT_MAIN_PAGE,ROLE_SUPER_ADMIN ]
        -   path: /admin/urest/main/faq/.*
            roles: [ ROLE_ADD_FAQ,ROLE_SUPER_ADMIN ]
        -   path: /admin/urest/main/(partner|aboutus)/.*
            roles: [ ROLE_EDIT_ABOUT_US,ROLE_SUPER_ADMIN ]
        -   path: /admin/urest/main/customtourorder/.*
            roles: [ ROLE_ORDER_PROCESSING,ROLE_SUPER_ADMIN ]
        -   path: /admin/my-tours/.*
            roles: [ ROLE_ORDER_PROCESSING,ROLE_SUPER_ADMIN ]


        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: '^/[^/]+/admin/',                     roles: [ ROLE_ADMIN, ROLE_SONATA_ADMIN ] }

        - { path: ^/.*,                                 role: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN:                         [ ROLE_USER, ROLE_SONATA_ADMIN ]
        ROLE_SUPER_ADMIN:                   [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

        ROLE_ADD_EDIT_SUPER_ADMIN:          [ ROLE_SONATA_ADMIN ]
        ROLE_ADD_EDIT_ADMIN:                [ ROLE_SONATA_ADMIN ]
        ROLE_ADD_EDIT_SUPER_MANAGER:        [ ROLE_SONATA_ADMIN ]
        ROLE_ADD_EDIT_EDITOR:               [ ROLE_SONATA_ADMIN ]
        ROLE_ADD_EDIT_MANAGER:              [ ROLE_SONATA_ADMIN ]
        ROLE_ADD_EDIT_USER:                 [ ROLE_SONATA_ADMIN ]
        ROLE_ADD_EDIT_CITY_COUNTRY:         [ ROLE_SONATA_ADMIN ]
        ROLE_ADD_EDIT_TOURS:                [ ROLE_SONATA_ADMIN ]
        ROLE_ADD_EDIT_INFO_IN_TOUR_BUILDER: [ ROLE_SONATA_ADMIN ]
        ROLE_ADD_EDIT_BLOG_SECTION:         [ ROLE_SONATA_ADMIN ]
        ROLE_ADD_EDIT_BLOG_ARTICLE_META:    [ ROLE_SONATA_ADMIN ]
        ROLE_ADD_EDIT_ARTICLE:              [ ROLE_SONATA_ADMIN ]
        ROLE_ADD_EDIT_CONTACTS:             [ ROLE_SONATA_ADMIN ]
        ROLE_ORDER_PROCESSING:              [ ROLE_SONATA_ADMIN ]
        ROLE_ORDER_STATISTIC:               [ ROLE_SONATA_ADMIN ]
        ROLE_EDIT_MAIN_PAGE:                [ ROLE_SONATA_ADMIN ]
        ROLE_ADD_PHOTO_VIDEO_FOOTER:        [ ROLE_SONATA_ADMIN ]
        ROLE_ADD_FAQ:                       [ ROLE_SONATA_ADMIN ]
        ROLE_EDIT_ABOUT_US:                 [ ROLE_SONATA_ADMIN ]
        ROLE_MODERATE_REVIEWS:              [ ROLE_SONATA_ADMIN ]