<?php

namespace Netcast\Urest\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApartmentTypeRepository extends EntityRepository
{
    public function findTypes($lang = 'en')
    {
        return $this->findBy(['lang'=>$lang]);
    }
}
