<?php

namespace Netcast\Urest\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
    public function search($term,$lang)
    {
        $qb = $this->createQueryBuilder('city')
            ->select(['country.title','country.id','city.title as ct','city.id as ci'])
            ->join('city.region', 'region')
            ->join('region.country', 'country', 'WITH', 'region.country = country.id')
            ->where('city.lang = :lang')
            ->andWhere('city.title LIKE :term')
            ->setParameter('lang', $lang)
            ->setParameter('term', '%'.$term.'%')
        ;
        return $qb->getQuery()->getResult();

    }
}
