<?php

namespace Netcast\Urest\MainBundle\Entity;

/**
 * CurrencyRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRateRepository extends \Doctrine\ORM\EntityRepository
{
}
