<?php

namespace Netcast\Urest\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FaqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqRepository extends EntityRepository
{
    /**
     * Get list of FAQ items.
     * If parameters is null then returned all items.
     * @param int|bool $active
     * @param int|bool $deleted
     * @param string $lang language alias en|ru|..etc
     * @return array
     */
    public function getList($active = null, $lang = null, $deleted=false)
    {
        $criteria = [];
        if (!is_null($active))
            $criteria['active'] = (int) $active;
        if (!is_null($lang))
            $criteria['lang'] = $lang;
        if ($deleted)
            $criteria['deleted'] = true;
        return $this->findBy($criteria);
    }
}
