<?php

namespace Netcast\Urest\MainBundle\Entity;

/**
 * FooterGalleryImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FooterGalleryImagesRepository extends \Doctrine\ORM\EntityRepository
{
}
