<?php

namespace Netcast\Urest\MainBundle\Entity;

/**
 * FooterGalleryVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FooterGalleryVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
