<?php

namespace Netcast\Urest\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends EntityRepository
{
    public function getList($active = 0, $display = 0)
    {
        $qb = $this->createQueryBuilder("language");
        
        if ($active) {
            $qb->andWhere('language.active = 1');
        }
        if ($display) {
            $qb->andWhere('language.display = 1');
        }
        return $qb->getQuery()->getResult();
    }
}
