<?php

namespace Netcast\Urest\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MainBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainBlockRepository extends EntityRepository
{
    /**
     * @param string(2) $lang
     * @return array
     */
    public function findBlocks($lang)
    {
        $qb = $this->createQueryBuilder('b')
            ->select('b')
            ->where('b.lang = :lang')
            ->setParameter('lang', $lang)
            ->setFirstResult(0)
            ->setMaxResults(3)
        ;
        return $qb->getQuery()->getResult();
    }
}
