<?php

namespace Netcast\Urest\MainBundle\Entity;

/**
 * PayOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
