<?php

namespace Netcast\Urest\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WellcomeMsgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WellcomeMsgRepository extends EntityRepository
{
    /**
     * Get list of Wellcome message by language
     * @param string $lang language alias en|ru|..etc
     * @return array
     */
    public function getMessages($lang='en')
    {
        return $this->findBy(['lang'=>$lang]);
    }
}
