Netcast\Urest\MainBundle\Entity\AboutUs:
    type: entity
    table: about_us
    indexes:
        about_user_idx:
            columns: [ user_id ]
        about_lang_idx:
            columns: [ lang ]
        about_image_idx:
            columns: [ image_id ]
    repositoryClass: Netcast\Urest\MainBundle\Entity\AboutUsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lang:
            type: string
            length: '2'
        title:
            type: string
            length: '255'
        content:
            type: text
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: true

    manyToOne:
         user:
              targetEntity: Application\Sonata\UserBundle\Entity\User
              joinColumn:
                name: user_id
                referenceColumnName: id
         image:
            targetEntity: Application\Sonata\MediaBundle\Entity\Media
            joinColumn:
              name: image_id
              referenceColumnName: id
            cascade: ["persist"]
    lifecycleCallbacks: {  }
