Netcast\Urest\MainBundle\Entity\BlogPostContent:
    type: entity
    table: blog_post_content
    indexes:
        tour_idx:
            columns: [ post_id ]
        lang_idx:
            columns: [ lang_id ]
    id:
      id:
        type: integer
        generator:
          strategy: AUTO
    fields:
      title:
         type: string
         length: 255
      content:
         type: text
      preview_text:
         type: string
         length: 255
         options:
           default: ''
    manyToOne:
      post:
        targetEntity: Netcast\Urest\MainBundle\Entity\BlogPost
        joinColumn:
          name: post_id
          referenceColumnName: id
      lang:
        targetEntity: Netcast\Urest\MainBundle\Entity\Language
        joinColumn:
          name: lang_id
          referenceColumnName: id