Netcast\Urest\MainBundle\Entity\BlogTagContent:
    type: entity
    table: blog_tag_content
    indexes:
        tag_idx:
            columns: [ parent_id ]
        blogtag_lang_idx:
            columns: [ lang_id ]
    id:
        id:
            type: integer
            generator:
              strategy: AUTO
    fields:
      title:
         type: string
         length: 255
    manyToOne:
      parent:
        targetEntity: Netcast\Urest\MainBundle\Entity\BlogTag
        joinColumn:
          name: parent_id
          referenceColumnName: id
      lang:
        targetEntity: Netcast\Urest\MainBundle\Entity\Language
        joinColumn:
          name: lang_id
          referenceColumnName: id