Netcast\Urest\MainBundle\Entity\BlogCategory:
    type: entity
    table: blog_category
    indexes:
        blogcategory_user_idx:
            columns: [ user_id ]
        blogcategory_alias_idx:
            columns: [ alias ]
    repositoryClass: Netcast\Urest\MainBundle\Entity\BlogCategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userId:
            type: integer
            column: user_id
        alias:
            type: string
            unique: true
            length: 255
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false
    oneToMany:
         posts:
             targetEntity: BlogPost
             mappedBy: category
         category_content:
             targetEntity: BlogCategoryContent
             mappedBy: parent
             cascade: ["all"]
             orphanRemoval: true
    manyToOne:
          user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            joinColumn:
              name: user_id
              referenceColumnName: id
    lifecycleCallbacks: {  }