Netcast\Urest\MainBundle\Entity\BlogCategoryContent:
    type: entity
    table: blog_category_content
    indexes:
        tour_idx:
            columns: [ parent_id ]
        lang_idx:
            columns: [ lang_id ]
    id:
      id:
        type: integer
        generator:
          strategy: AUTO
    fields:
      title:
         type: string
         length: 255
    manyToOne:
      parent:
        targetEntity: Netcast\Urest\MainBundle\Entity\BlogCategory
        joinColumn:
          name: parent_id
          referenceColumnName: id
      lang:
        targetEntity: Netcast\Urest\MainBundle\Entity\Language
        joinColumn:
          name: lang_id
          referenceColumnName: id