Netcast\Urest\MainBundle\Entity\BlogTag:
    type: entity
    table: blog_tag
    indexes:
        blogtag_user_idx:
            columns: [ user_id ]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userId:
            type: integer
            column: user_id
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false
        frequency:
            type: integer
            options:
              default: 0
    oneToMany:
        tag_content:
            targetEntity: BlogTagContent
            mappedBy: parent
            cascade: ["all"]
            orphanRemoval: true

    manyToOne:
        user:
          targetEntity: Application\Sonata\UserBundle\Entity\User
          joinColumn:
            name: user_id
            referenceColumnName: id
    manyToMany:
        posts:
          targetEntity: BlogPost
          mappedBy: tags
    lifecycleCallbacks: {  }
