Netcast\Urest\MainBundle\Entity\Faq:
    type: entity
    table: faq
    indexes:
        faq_user_idx:
            columns: [ user_id ]
    repositoryClass: Netcast\Urest\MainBundle\Entity\FaqRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userId:
            type: integer
            column: user_id
            nullable: false
        datePublish:
            type: date
            nullable: false
        active:
            type: boolean
            options:
              default: 1
        deleted:
            type: boolean
            options:
              default: 0
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false
    oneToMany:
          faq_content:
              targetEntity: FaqContent
              mappedBy: parent
              cascade: ["all"]
              orphanRemoval: true
    manyToOne:
          user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            joinColumn:
              name: user_id
              referenceColumnName: id
    lifecycleCallbacks: {  }
