Netcast\Urest\MainBundle\Entity\FooterGalleryImages:
    type: entity
    table: gallery_img
    repositoryClass: Netcast\Urest\MainBundle\Entity\FooterGalleryImagesRepository
    id:
      id:
        type: integer
        generator:
          strategy: AUTO
    fields:
      title:
          type: string
          length: 255
      active:
          type: boolean
          default: 1
      lang:
          type: string
          length: '2'
          nullable: false
    manyToOne:
      media:
        targetEntity: Application\Sonata\MediaBundle\Entity\Media
        joinColumn:
          name: media_id
          referenceColumnName: id
        cascade: ["persist"]
