Netcast\Urest\MainBundle\Entity\Hotel:
    type: entity
    table: hotels
    indexes:
        city_region_idx:
            columns: [ city_id ]
        city_user_idx:
            columns: [ user_id ]
    repositoryClass: Netcast\Urest\MainBundle\Entity\HotelRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        stars_count:
            type: integer
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: true

    manyToOne:
         city:
             targetEntity: City
             inversedBy: hotels
             joinColumn:
                name: city_id
                referencedColumnName: id
         user:
             targetEntity: Application\Sonata\UserBundle\Entity\User
             joinColumn:
                 name: user_id
                 referenceColumnName: id

    oneToMany:
            hotel_content:
                targetEntity: HotelContent
                mappedBy: parent
                cascade: ["all"]
                orphanRemoval: true
            rooms:
                targetEntity: HotelRoom
                mappedBy: hotel
                cascade: ['persist', 'remove']
                orphanRemoval: true

            images:
                targetEntity: HotelImages
                mappedBy: hotel
                cascade: ['persist', 'remove']
                orphanRemoval: true

    manyToMany:
            video:
                targetEntity: Application\Sonata\MediaBundle\Entity\Media
                inversedBy: hotel
                cascade: ['persist', 'remove']