Netcast\Urest\MainBundle\Entity\OptionImages:
  type: entity
  table: option_images
  indexes:
      location_info_idx:
          columns: [ option_id ]
      image_idx:
          columns: [ media_id ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    main:
      type: boolean
      options:
          default: false
  manyToOne:
    option:
      targetEntity: Options
      inversedBy: images
    media:
      targetEntity: Application\Sonata\MediaBundle\Entity\Media
      joinColumn:
        name: media_id
        referenceColumnName: id
      cascade: ['persist', 'remove']
