Netcast\Urest\MainBundle\Entity\Region:
    type: entity
    table: region
    indexes:
        region_parent_idx:
            columns: [ country_id ]
        country_user_idx:
            columns: [ user_id ]
    repositoryClass: Netcast\Urest\MainBundle\Entity\RegionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        coordinates:
            type: string
            length: '255'
            default: ''
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: true

    oneToMany:
         region_content:
              targetEntity: RegionContent
              mappedBy: parent
              cascade: ["all"]
              orphanRemoval: true
         cities:
              targetEntity: City
              mappedBy: region
              cascade: ['persist', 'remove']
    manyToOne:
         country:
             targetEntity: Country
             inversedBy: regions
             joinColumn:
                 name: country_id
                 referencedColumnName: id
         user:
              targetEntity: Application\Sonata\UserBundle\Entity\User
              joinColumn:
                name: user_id
                referenceColumnName: id
    lifecycleCallbacks: {  }
